### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chaimhaas**
Another slight edit to the product description

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Review by godlygeek — CHANGES_REQUESTED** [review]
I'd rather change:

> in order to help you learn easily and quickly

to:

> helping you quickly and easily learn

That sounds a little more natural, and conversational, to my ears.

**Comment by chaimhaas** [comment]
It is grammatically incorrect though....

You're not supposed to put "quickly and easily" between [to] and the verb.

I'd be okay with "helping you learn quickly and easily"

**Comment by godlygeek** [comment]
> I'd be okay with "helping you learn quickly and easily"

Let's just drop the "to", then - "helping you quickly and easily learn"

**Comment by chaimhaas** [comment]
Ok -- "helping you quickly and easily learn"

**Comment by godlygeek** [comment]
> You're not supposed to put "quickly and easily" between [to] and the verb.

For what it's worth, though: MLA says it's fine. :) https://style.mla.org/split-infinitives/

**Review by godlygeek — APPROVED** [review]
I made that change, and one other small tweak ("what it is doing" to "what it's doing" in the same sentence, to sound more conversational). After those changes, this looks good to me.

**Comment by godlygeek** [comment]
@pablogsal Seems like I need a review from someone who isn't me 😄

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
