### PR TITLE
Reach 100% python coverage rate

### PR DESCRIPTION
**Pull request by yize415**
*Issue number of the reported bug or feature request: #51 *

**Describe your changes**
1. More tests are introduced in this PR such that `make pycoverage` returns 100% coverage rate. 
2. Coverage requirement is bumped from 97% to 100%.
3. Test files are no longer excluded from coverage report.

**Testing performed**
make check

**Additional context**

### CODE REVIEW

**Comment by godlygeek** [comment]
@yize415 Thanks, this looks awesome! Would you mind editing your commit messages to add the [DCO signoff](https://github.com/bloomberg/pystack/blob/main/CONTRIBUTING.md#contribution-licensing)? You can squash both of these into one commit at the same time, too.

From the state your PR is in now, you can run:
```shell
git reset --soft d2b425be1389bf151043c366212a12a3d437f27a
```
to revert your commits but leave your changes staged, and then you can run:
```shell
git commit -s -m "tests: Reach 100% Python code coverage"
```
to re-commit your changes as a single commit and with the DCO signoff added.

**Comment by yize415** [comment]
Thanks for instruction! I just force-pushed and let me know if further actions are needed

**Comment by pablogsal** [comment]
@yize415 Unfortunately some of the latest merges have created conflicts with this PR. Would you mind solving them so we can merge? If you have problems you can ping me (@pablogsal ) or ask @godlygeek for help!

**Comment by yize415** [comment]
Just solved merge conflicts and rebased!

**Review by godlygeek — APPROVED** [review]
LGTM

**Comment by godlygeek** [comment]
Thanks so much for the contribution, @yize415!

**Pull request merged**
